# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.IntegerField()),
                ('good', models.IntegerField()),
                ('bad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=1024)),
                ('author', models.CharField(max_length=64)),
                ('put_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='essay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Essay'),
        ),
    ]
