# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='put_date',
            new_name='pub_date',
        ),
    ]
